---
functional:
  - Пользователь должен иметь возможность создавать лобби с игрой
  - Пользователь должен иметь возможность просматривать список лобби
  - Пользователь должен иметь возможность подключатся к лобби
  - Пользователь должен иметь возможность просматривать список игроков в онлайне
  - Пользователь должен иметь возможность просматривать историю прошедших игр
  - Пользователь должен иметь возможность просматривать список лидеров (общий/недельный/месячный)
  - Пользователь должен иметь возможность зайти на сайт под учётной записью Github/Discord
  - Пользователь должен иметь возможность общаться в общем чате с другими игроками
  - Пользователь должен иметь возможность видеть кол-во игроков в режиме онлайн
  - Пользователь должен иметь возможность просматривать текущие турниры
  - Пользователь должен иметь возможность просматривать прошедшие турниры
  - Пользователь должен иметь возможность язык программирования
  - Пользователь должен иметь возможность отправить ссылку на игру для подключения
  - Пользователь должен иметь возможность зайти зрителем в игру
  - Пользователь должен иметь возможность при создании игры выбирать уровень сложности, тип, ограничение по времени, название игры или по тэгам
  - Пользователь должен иметь возможность в игре видеть код противника в реальном времени
  - Пользователь должен иметь возможность общаться в чате с противником
  - Пользователь должен иметь возможность провести тест для проверки кода
  - Пользователь должен иметь возможность сбросить код
  - Пользователь должен иметь возможность сдаться
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен иметь защиту от различных хаккерских атак
  - Сайт обрабатывать большое кол-во трафика
   
